# Generated by Django 5.0.6 on 2024-06-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
