# Generated by Django 5.0.6 on 2024-07-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
